apiVersion: apps/v1 
kind: Deployment
metadata:
  name: myapp
  namespace: test-ns 
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
--- 
apiVersion: v1 
kind: Service
metadata:
  name: myapp
  namespace: test-ns
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
