version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use a CircleCI-provided Python image as a base
    steps:
      - checkout  # Check out your code from the repository
      - run:
          name: Build and push image
          command: |
            docker build -t helloworld:latest .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag helloworld:latest 7618/helloworld:latest
            docker push 7618/helloworld:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
