version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run: mvn clean install
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --tag my-image:latest \
              --build-arg WAR_FILE=target/my-app.war \
              .
